apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: deployment-blockchain-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blockchain-client
  template:
    metadata:
      labels:
        app: blockchain-client
    spec:
      containers:
      - name: blockchain-client
        image: sadist/blockchain-client
        imagePullPolicy: Always